### PR TITLE
remove(event bus)

### LINKED ISSUE #47: Remove event bus
I'm honestly not too sure how useful this functionality is, but I just had a look at it adds quite a bit of weight to the project. I've personally never used it, and I can't imagine many other people do because most of the time they're going to be doing events with their Alpine components using `$dispatch`.

### PR DESCRIPTION
**Pull request by ryangjchandler**
Closes #47 - this reduced the bundle size (brotli) by about 900kb which is pretty crazy. It was already small but I have never personally used this functionality and I can't imagine many people will.

This won't be added to v1 because it's a breaking change so would be for a v2 release, but I figured I'd add it here to that it can be merged in whenever.

### CODE REVIEW

**Comment by viniciussbs** [comment]
Is there a way to opt into the breaking change? I would like to use Spruce without the event bus in the bundle.

**Comment by ryangjchandler** [comment]
@viniciussbs - this won't be changed until v2.0.0, the alternative approach would be having a `spruce-lite` build that doesn't have any of this stuff in, but that's a maintenance nightmare.

**Comment by viniciussbs** [comment]
Yep, not worth it. Thanks!

**Comment by ryangjchandler** [comment]
@viniciussbs No worries - glad to see somebody else that doesn't want the event bus.

**Pull request merged**
