### PR TITLE
wip(version 1 rewrite)

### PR DESCRIPTION
**Pull request by ryangjchandler**
This PR will track the progress for the first major release of Spruce. Below is a list of changes that need to be made before that can happen:

* [x] Drop support for Alpine < 2.5.0
* [x] Remove global store configuration options
* [x] Rename `init` event to `beforeMount`
* [x] Add new `mounted` event
* [x] Remove the need for `x-subscribe` directive.
* [x] Hook into Alpine via the `magicProperties` option.
* [ ] Update test suite
* [ ] Implement dependency tracking **(?)**

### CODE REVIEW

**Comment by ryangjchandler** [comment]
Made good progress on this to be fair. Instead of having a custom proxy implementation, everything runs through Alpine's internals. 

The basic idea is, instead of looking for a custom directive to replace with some custom code, Spruce creates a "void" Alpine component. 

From there, everything references that component greatly reducing the heavy lifting that Spruce needs to do. 

All components instantly have access to the global store, which means that version 1 will only support Alpine >= 2.5 (using the custom magic properties API). 

Watchers are also running through Alpine, again reducing the amount of heavy lifting Spruce needs to do. 

The test suite needs to be re-worked to support the new API, and there might be some breaking changes, but that's okay since it's a new major version.

**Comment by ryangjchandler** [comment]
@HugoDF - can you think of anyway to work around the whole including script before Alpine thing?

Since this relies on DOM manipulation before Alpine starts, I'm not sure what can be done..

**Comment by HugoDF** [comment]
I think you can use `addMagicProperty` instead of mutating the `magicProperties` field I think.

There isn't going to be a workaround for the loading, since like you said, DOM manipulation/attaching `deferLoadingAlpine`.

**Comment by ryangjchandler** [comment]
> 
> 
> I think you can use `addMagicProperty` instead of mutating the `magicProperties` field I think.
> 
> There isn't going to be a workaround for the loading, since like you said, DOM manipulation/attaching `deferLoadingAlpine`.

Good point, just saw that method on the object.

**Comment by ryangjchandler** [comment]
I've made some progress on this one. The only problem I've got so far is that watching for state changes is rather difficult using Alpine as the intermediary. 

Since deep watchers aren't a thing, I can't just watch for any changes on the `stores` property so I might go for a different approach after all. I was able to get it back to a single KB which is cool. 

I might also see if I can use Alpine _just_ to create the Proxy since that is where a lot of the bulk comes from, as well as the watchers. The changes above actually use the Alpine component to register watchers so any fixes or changes to Alpine's watchers will be supported with Spruce too.

**Pull request closed without merging**
