### PR TITLE
Add support for "watching" state updates

### LINKED ISSUE #22: Add core events
Now that #21 has been merged, I can add some core events that get fired. 

Based on the discussion in #12, I want to add a `spruce:updating` and `spruce:updated` hook. I'll also add an `init` hook.

### PR DESCRIPTION
**Pull request by ryangjchandler**
This PR closes #22. I've actually decided not to add the `spruce:updating` and `spruce:updated` events and instead opt for the `Spruce.watch()` approach as suggested by @HugoDF.

This approach works much better for nested / dot notated properties.

To do:

* [x] Write tests
* [x] Update README

### CODE REVIEW

**Comment by ryangjchandler** [comment]
@HugoDF anything obviously wrong here? No rush of course, not planning on tagging until this is merged tomorrow :)

**Comment by HugoDF** [comment]
@ryangjchandler there's one weird case I can think of which is: what happens if you try to update store state from within the callback? Infinite loop?

**Comment by ryangjchandler** [comment]
> @ryangjchandler there's one weird case I can think of which is: what happens if you try to update store state from within the callback? Infinite loop?

Ah yeah, infinite loops. I guess this is kind of down to the developer, since even if I didn't pass the state to the callback, they could still modify using `Spruce.state()` etc.

**Comment by HugoDF** [comment]
@ryangjchandler my intuition was that you could pass back a flag to stop the update or something? I feel like this might be going into feature creep territory.

**Comment by ryangjchandler** [comment]
> @ryangjchandler my intuition was that you could pass back a flag to stop the update or something? I feel like this might be going into feature creep territory.

Yeah, maybe a flag would do it.

**Pull request merged**
